name: "🚀 Propozycja nowej funkcjonalności"
description: "Zaproponuj nową funkcję lub usprawnienie"
title: "[FEAT] - Opis funkcjonalności"
labels: ["feature"]
body:
  - type: textarea
    id: opis_z_uzasadnieniem
    attributes:
      label: "📝 Opis funkcjonalności i dlaczego jest potrzebna"
      description: "Opisz, co chcesz dodać i dlaczego i jakie problemy to rozwiąże."
      placeholder: "Przykład: Dodanie trybu ciemnego dla lepszej czytelności w nocy."
    validations:
      required: true

  - type: textarea
    id: rozwiazanie
    attributes:
      label: "💡 Możliwe rozwiązanie"
      description: "Jak według Ciebie można to zaimplementować?"
      placeholder: "Dodać przełącznik trybu ciemnego w ustawieniach."

  - type: textarea
    id: dodatkowe_info
    attributes:
      label: "📎 Dodatkowe informacje"
      description: "Czy masz jakieś zrzuty ekranu, logi lub inne istotne informacje?"
