name: "🛠️ Zadanie"
description: "Zadanie do wykonania w projekcie"
title: "[TASK] - Opis zadania"
labels: ["task", "do zrobienia"]
body:
  - type: textarea
    id: opis
    attributes:
      label: "📋 Opis zadania"
      description: "Co należy zrobić?"
      placeholder: "Przykład: Zaimplementować logowanie użytkownika przez OAuth2."
    validations:
      required: true

  - type: textarea
    id: kryteria
    attributes:
      label: "✅ Kryteria akceptacji"
      description: "Jakie warunki muszą być spełnione, aby zadanie było uznane za zakończone?"
      placeholder: "1. Użytkownik może się logować przez Google\n2. Dane są przechowywane poprawnie w bazie"

  - type: textarea
    id: dodatkowe_info
    attributes:
      label: "📎 Dodatkowe informacje"
      description: "Czy są jakieś dodatkowe informacje, linki do dokumentacji itp.?"
